version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.1
    - 2.25.2
    - 2.26.0
    - 2.27.1
    - 2.28.0
    - 2.28.1
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.2
    - 2.30.3
    - 2.31.0
    - 2.32.0
    - 2.32.1
    - 2.33.0
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.37.1
    - 2.37.2
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.71
    - 8.10.72
    - 8.10.73
    - 8.10.75
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@slack/web-api"
    versions:
    - 6.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
