version: 0.2

env:
  secrets-manager:
    SLACK_TOKEN: codebuild/keyakizaka46-schedule-slack-notifier:SLACK_TOKEN
    SLACK_CHANNEL: codebuild/keyakizaka46-schedule-slack-notifier:SLACK_CHANNEL

phases:
  pre_build:
    commands:
      - yarn --pure-lockfile
  build:
    commands:
      - ./scripts/deploy.sh
