service:
  name: keyakizaka46-schedule-slack-notifier

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage}
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    TZ: JST
    SERVERLESS_STAGE: ${opt:stage}
  timeout: 30
  memorySize: 256

custom:
  webpack:
    excludeFiles:
      - '**/*.test.js'

functions:
  notify:
    handler: src/handler.notify
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - schedule: cron(0 1 * * ? *)

  healthz:
    handler: src/handler.healthz
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http: GET healthz
