service:
  name: keyakizaka46-schedule-slack-notifier

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: production
  environment:
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    TZ: JST
  timeout: 30
  memory: 256

functions:
  notify:
    handler: src/handler.notify
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - schedule: cron(0 1 * * ? *)
