version: '2.1'

commands:
  setup_npm_packages:
    description: 'Install NPM packages and cache them'
    steps:
      - restore_cache:
          keys:
            - v2-npm-{{ arch }}-{{ checksum "yarn.lock" }}
            - v2-npm-{{ arch }}
      - run:
          command: yarn --pure-lockfile
      - save_cache:
          key: v2-npm-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  run_tests:
    description: 'Run tests and upload coverage to artifacts'
    steps:
      - run:
          command: yarn test --coverage
      - store_artifacts:
          path: coverage

jobs:
  package:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - setup_npm_packages
      - run_tests
      - run:
          name: package
          command: yarn package

  deploy:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - setup_npm_packages
      - run_tests
      - run:
          name: deploy
          command: yarn deploy

workflows:
  version: 2

  build:
    jobs:
      - package:
          filters:
            branches:
              ignore:
                - master

  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
