name: test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - src/**.ts
      - .nvmrc
      - jest.config.js
      - tsconfig.json
      - webpack.config.js
      - yarn.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yaml
      - src/**.ts
      - .nvmrc
      - jest.config.js
      - tsconfig.json
      - webpack.config.js
      - yarn.lock

jobs:
  test:
    name: Run yarn test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '12'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --pure-lockfile

      - run: yarn serverless invoke local -f healthz
      - run: yarn test
